site_name: Podman Files
theme:
  name: material
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.footer
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - toc.integrate
    - search.suggest

plugins:
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

repo_name: dkvc/podman-files
repo_url: https://github.com/dkvc/podman-files
copyright: Copyright &copy; MIT License

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/dkvc/
          
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/in/dkvc/

# Page Tree
nav:
  - Home: index.md
  - NVIDIA Installation: nvidia-installation/index.md
  - Tensorflow Installation: tensorflow-installation/index.md
  - Container: create-container/index.md
  - Running a GUI: running-gui/index.md